### ISSUE TITLE
Disable windows

### ISSUE THREAD

**Issue by Dontmindmes** [ProtonMail/go-autostart#15]
How can I disable windows start up for this? I already made my own for windows

**Comment by emersion** [comment]
You can use build tags. For instance:

`autostart_windows.go`:

```go
[code that uses your custom thing]
```

`autostart_no_windows.go`:

```go
//+build !windows

[code that uses go-autostart]
```

**Comment by Dontmindmes** [comment]
No i mean in the code

how can i only allow linux and mac to install and not windows
`app := &autostart.App{
		Name: "test",
		DisplayName: "Just a Test App",
		Exec: []string{"bash", "-c", "echo autostart >> ~/autostart.txt"},
	}

	if app.IsEnabled() {
		log.Println("App is already enabled, removing it...")

		if err := app.Disable(); err != nil {
			log.Fatal(err)
		}
	} else {
		log.Println("Enabling app...")

		if err := app.Enable(); err != nil {
			log.Fatal(err)
		}
	}`

**Comment by emersion** [comment]
`autostart_no_windows.go`:

```go
//+build !windows

package whatever

import (
	"log"
	"github.com/ProtonMail/go-autostart"
)

func DoIt() {
	app := &autostart.App{
		Name: "test",
		DisplayName: "Just a Test App",
		Exec: []string{"bash", "-c", "echo autostart >> ~/autostart.txt"},
	}

	if app.IsEnabled() {
		log.Println("App is already enabled, removing it...")

		if err := app.Disable(); err != nil {
			log.Fatal(err)
		}
	} else {
		log.Println("Enabling app...")

		if err := app.Enable(); err != nil {
			log.Fatal(err)
		}
	}

	log.Println("Done!")
}
```

`autostart_windows.go`:

```go
package whatever

func DoIt() {
	// Use your thing
}
```

**Comment by emersion** [comment]
Just to disambiguate: build tags are the best solution because they save you from building the C code of go-autostart on Windows. I don't think it makes sense to add a mechanism in go-autostart to select which platforms are affected since callers can easily do it.
